version: "3.6"
services:
  redis-master1:
     image: redis-cluster
     container_name: redis-master1
     working_dir: /config
     environment:
       - PORT=6391
     ports:
       - "6391:6391"
       - "16391:16391"
     stdin_open: true
     networks:
        redis-master:
          ipv4_address: 172.20.0.2
     tty: true
     privileged: true
     volumes: ["/data/docker/redis-cluster/conf:/config"]
     entrypoint:
       - /bin/bash
       - redis.sh
  redis-master2:
       image: redis-cluster
       working_dir: /config
       container_name: redis-master2
       environment:
              - PORT=6392
       networks:
          redis-master:
             ipv4_address: 172.20.0.3
       ports:
         - "6392:6392"
         - "16392:16392"
       stdin_open: true
       tty: true
       privileged: true
       volumes: ["/data/docker/redis-cluster/conf:/config"]
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-master3:
       image: redis-cluster
       container_name: redis-master3
       working_dir: /config
       environment:
              - PORT=6393
       networks:
          redis-master:
            ipv4_address: 172.20.0.4
       ports:
         - "6393:6393"
         - "16393:16393"
       stdin_open: true
       tty: true
       privileged: true
       volumes: ["/data/docker/redis-cluster/conf:/config"]
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-slave-1:
       image: redis-cluster
       container_name: redis-slave-1
       working_dir: /config
       environment:
            - PORT=6394
       networks:
          redis-slave:
             ipv4_address: 172.30.0.2
       ports:
         - "6394:6394"
         - "16394:16394"
       stdin_open: true
       tty: true
       privileged: true
       volumes: ["/data/docker/redis-cluster/conf:/config"]
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-salve-2:
       image: redis-cluster
       working_dir: /config
       container_name: redis-slave-2
       environment:
             - PORT=6395
       ports:
         - "6395:6395"
         - "16395:16395"
       stdin_open: true
       networks:
          redis-slave:
              ipv4_address: 172.30.0.3
       tty: true
       privileged: true
       volumes: ["/data/docker/redis-cluster/conf:/config"]
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-salve-3:
       image: redis-cluster
       container_name: redis-slave-3
       working_dir: /config
       environment:
          - PORT=6396
       ports:
         - "6396:6396"
         - "16396:16396"
       stdin_open: true
       networks:
          redis-slave:
            ipv4_address: 172.30.0.4
       tty: true
       privileged: true
       volumes: ["/data/docker/redis-cluster/conf:/config"]
       entrypoint:
         - /bin/bash
         - redis.sh
networks:
  redis-master:
     driver: bridge
     ipam:
       driver: default
       config:
          -
           subnet: 172.20.0.0/16
  redis-slave:
       driver: bridge
       ipam:
         driver: default
         config:
            -
             subnet: 172.30.0.0/16